--- #YAML:1.0
name: Module-MakefilePL-Parse
version: 0.05
author: Robert Rothenberg <rrwo at cpan.org>
abstract: parse required modules from Makefile.PL
license: perl
requires:
  perl: 5.6.1
build_requires:
  Test::More: 0
  Test::Warn: 0
provides: {}
generated_by: Module::Build version 0.25
