--- #YAML:1.0
name: Module-MakefilePL-Parse
version: 0.11
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: parse required modules from Makefile.PL
license: perl
requires:
  Text::Balanced: 0
  enum: 1.016
  perl: 5.6.1
build_requires:
  Test::More: 0
  Test::Warn: 0
provides:
  Module::MakefilePL::Parse:
    file: lib/Module/MakefilePL/Parse.pm
    version: 0.11
generated_by: Module::Build version 0.25_02
